---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kv-csi-driver
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: edge-source
  path: ./deploy/kv-csi-driver
  prune: true
  validation: client
  healthChecks:
    - kind: DaemonSet
      name: kv-csi-driver-csi-secrets-store-provider-azure
      namespace: kv-csi-driver
    - kind: DaemonSet
      name: kv-csi-driver-secrets-store-csi-driver
      namespace: kv-csi-driver
