---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: pod-identity
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: edge-source
  path: ./deploy/aad-pod-identity
  prune: true
  validation: client
  healthChecks:
  - kind: DaemonSet
  name: aad-pod-identity-nmi
  namespace: aad-pod-identity
