---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portainer
  namespace: flux-system
spec:
  chart:
    spec:
      chart: portainer
      sourceRef:
        kind: HelmRepository
        name: portainer-repo
  values:
    service:
      type: ClusterIP
  interval: 5m0s
  releaseName: portainer
  targetNamespace: portainer