apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aad-pod-identity-creds
  namespace: default
spec:
  encryptedData:
    clientsecret: AgChMi9+xKZpVvtv3zwyRSrCM8YLEzUtCU2QcgqngYIS1Yf7jd+pAF4ArETgWlWd4AD5iUVm6DkBpWLoRXp4GsizB9is6BvJJUvuW8XBsCFy8j84pXST9sNBgKgOLO63/XMtAYdorXDBeremaMeGi+XBHWYPP11TGj1j5hVi2/T9rbMTW6b2DEM3GA2Rrh4rKXFDad8Vdvvon0HWidgm7FMfWRuT/WroDLeANJmV5I6P4uVk5tZ7ocwDdyXgBAgFDUmPffvnqPSY9I0sqb/ddc6ASm82NfFASL2SapfCniJH5F6PpTq6Awiqbna6ahjLevjtF7A28Ki6Ld5iCRrmDSCOLofSYAGu6o7xl8lx1LgQTBq6OFco7wUV15kNFw5vDJmKMAkkmcha241OrD7xiAySv8qtImyB4i9e8qqXK3R+CBt07Uqm8JBdo237omoRj98fhFtdMN7ZoyBAq6bqESUonkpDKWxPFuw0+AgHGpwCID5gq8hUDIRe+F8fMXAu6UKxbRter5tJeL7Jit4Ww3NVVL9vvkwA3O/cVwLmDHYBBUv8VevV3UIMEZhwRXynno+xHH2UIzZeELHl6DbskVIUOB0TVqEMM9KB1iIdmRES88ncO/VctHsffGkgs86bWd7upIPUqZZrgqYV2uQ58PzkjicHwxIpknmV9wLe5KQySzLsJ9Iwa9WCG2TmNNnuMHuz3EWLBXcNgZQywYEJ5nUgsK2JXNR0fyjnBvIeTa+9A3re
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aad-pod-identity-creds
      namespace: default

