---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: identity-test
spec:
  type: 1
  tenantID: 
  clientID: d2416969-1936-4fe3-ad65-7471d9e69a46
  clientPassword: {"name":"aad-pod-identity-creds","namespace":"default"}
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: identity-test-binding
spec:
  azureIdentity: "identity-test"
  selector: "identity-test"
