---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: identity-test
spec:
  type: 1
  tenantID: 72f988bf-86f1-41af-91ab-2d7cd011db47
  clientID: f3e46c7e-fe79-41c9-b4ed-7dde6a1e24b4
  clientPassword: {"name":"aad-pod-identity-creds","namespace":"default"}
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: identity-test-binding
spec:
  azureIdentity: "identity-test"
  selector: "identity-test"
---
apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    aadpodidbinding: identity-test
spec:
  containers:
  - name: identity-test
    image: mcr.microsoft.com/oss/azure/aad-pod-identity/demo:v1.6.3
    args:
      - --subscriptionid=2e458de2-af10-484c-a5a5-6c259d9a907f
      - --clientid=f3e46c7e-fe79-41c9-b4ed-7dde6a1e24b4
      - --resourcegroup=azure-k8s
    env:
      - name: MY_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: MY_POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: MY_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
  nodeSelector:
    kubernetes.io/os: linux
