apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: akv2k8s-values.yaml
  namespace: flux-system
spec:
  encryptedData:
    values.yaml: AgBo676PUzgFRKlMuJeXFuI4b4siuTrqGRpsWs1c6/7dVUFpSd8v55xSLYs16zpfkcCqeV+TWBImOGFNAdiphVcZ8MR2KiDU27Axt3Fa2OetiJKD5Cj6fkZ0PRtZDnsKzYyTQo16GXzguDP+ioWteVytfN95JuRzagF8uubdbXBjNyxoxGvYOomhBdKC3EepkApbRxyOOg/MCF1nqpphtPekV9nXPd3DTk2mWT8l6KiLhT3enQ9V9N2coCXY6ByooY5T2yJh4dBLN6Ghq2kWhsAvBtmeufGVnw+cKw9RHyWKR0MoGogCEm2WyqHIuEgf52U7a9Qx3pQ/DzZvHRhVRorHbWuXwFCi8YQEW2HKK/lV3qo+ge19yI2JK84NgOWo6VVnmeijMx5czHWSTGGSDEzayMBRUdLL0E+9MeOoKEp3ND96HWkgv/LicZeLtXRzSdR/5PXG/ra1CVYaEuAjHhQ3Vnex1UzPycOKyfL1aJsZjiRn4U1EjTXwipdWosVGJeVFNc/dKMe57GIZtp9EDL7KZLnoToD/Oqr+ji69x/sTouLSR5LaMBtKq1zZTrnz2Rsc6YSadBS63gZ9TRqcxlEhB+rhx51RUnGebxJT+Z/sAE2/EkRCZKA0cpCCryRvNgTQJWAaT5t6VWax3n7euHk6F5B6MNbMAk0aw+eAL85YQ72vx9iFZw9XipKOEA792+XOdzGwYJQqmkCNMMDZrWq3t6TVYiLcb7zXzeNhb57Y/NCe/bbNE7ZX1xl+zvyBt0vm7YtiM/uNZ3xUysiI0gwUughBn804ksZZkSKMrsbcfzJYwKXSBbyS1yOu2gS3E/g8vuPQZeBXPOxvkHr2XaCrI6krOiRaA+RAdF4A32wrLgkKL0og+nDpryBhBKxHM0fawyanFkLHZ53NS18LkFm561qyZPQNzlbAU3y7beOHyRhvW7b/do5fJPGG7vfGJCE4eAdWvVQmL4NYJsGbIt6uVY+ejh6+QZcApQ0=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: akv2k8s-values.yaml
      namespace: flux-system
    type: Opaque

