---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kv-csi-driver
  namespace: flux-system
spec:
  chart:
    spec:
      chart: csi-secrets-store-provider-azure
      sourceRef:
        kind: HelmRepository
        name: kv-csi-driver
      version: '>=0.0.20-0'
  install: {}
  interval: 5m0s
  releaseName: kv-csi-driver
  targetNamespace: kube-system

