{{- $namespace := .Release.Namespace }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "env-debug.fullname" . }}
  labels:
    {{- include "env-debug.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "env-debug.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "env-debug.selectorLabels" . | nindent 8 }}
    spec:
    {{- if .Values.azure.enabled }}
      volumes:
        - name: azure-keyvault
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-keyvault
            nodePublishSecretRef:
              name: kv-creds
    {{- end }}
      containers:
        - image: gcr.io/kuar-demo/kuard-amd64:1
          name: kuard
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          {{- if .Values.azure.enabled }}
          volumeMounts:
            - name: azure-keyvault
              mountPath: "/mnt/azure-keyvault"
              readOnly: true
          {{- end }}
          env:
            - name: ALWAYS_STATIC
              value: "From Chart"
            - name: ALWAYS_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: {{ include "env-debug.fullname" . }}-config
                  key: MESSAGE
          {{- if .Values.env }}
          {{- range .Values.env }}
            - name: {{ .name }}
              {{- if .value }}
              value: {{ .value | quote }}
              {{- end }}
              {{- if .config }}
              valueFrom:
                configMapKeyRef:
                  name: {{ include "env-debug.fullname" . }}-config
                  key: {{ .config.key | quote }}
              {{- end }}
              {{- if .secret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secret.name | quote }}
                  key: {{ .secret.key | quote }}
              {{- end }}
          {{- end }}
          {{- end }}
