{{- $namespace := .Release.Namespace }}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-keyvault
  namespace: {{ $namespace }}
spec:
  provider: azure
  secretObjects:
  - secretName: key-vault-secrets
    type: Opaque
    data:
    - objectName: admin
      key: admin-password
  parameters:
    usePodIdentity: "false"
    keyvaultName: "{{ .Values.azure.keyvault }}"
    subscriptionId: "{{ .Values.azure.subscription }}"
    tenantId: "{{ .Values.azure.tenant }}"
    objects:  |
      array:
        - |
          objectName: admin
          objectType: secret
