---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aad-pod-identity
  namespace: flux-system
spec:
  chart:
    spec:
      chart: aad-pod-identity
      sourceRef:
        kind: HelmRepository
        name: aad-pod-identity
      version: '4.1.2'
  install:
    crds: Create
  interval: 5m0s
  releaseName: aad-pod-identity
  targetNamespace: aad-pod-identity
  upgrade:
    crds: CreateReplace
  values:
    operationMode: managed

