---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: aad-pod-identity
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts

