---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
  namespace: flux-system
spec:
  chart:
    spec:
      chart: keda
      version: 2.0.0
      sourceRef:
        kind: HelmRepository
        name: keda-repo
  interval: 5m0s
  releaseName: keda
  targetNamespace: keda