---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: certmgr
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: certmgr-repo
  values:
    installCRDs: true
  interval: 5m0s
  releaseName: certmgr
  targetNamespace: cert-manager