apiVersion: v1
kind: Secret
metadata:
    name: demoapp-credentials
    namespace: demoapp
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:fFKdSwE=,iv:WE0DC8nb03NrZ/zhtNPfHuMCKqFdSS3XolG2pJzyX1s=,tag:Az8PUaOfxs9YpQuoPdCI1w==,type:str]
    password: ENC[AES256_GCM,data:Xj81nuqYfR6dUw==,iv:iqweSxsRmmC4mO/cXydTgLYIqXPJdNicTNXamMcuZIg=,tag:GLQi1+ThjQhw4XfNEoke6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-10T18:31:21Z"
    mac: ENC[AES256_GCM,data:VpZ86DFk5vtTtRmBERNpvLbaVm/N38dT0qVdneL8kCUo5wxvrISvfxBxx0a3qMxrS99qoCKwI474YVxIwikfYMaWlue1I1exjhC4EBxPyVo14dOjhE9Iqj9QFKrln9PGei+ITJNitnRYW7ZV9O2DOi56lKUiHi/kutxBfVA/Zsw=,iv:Q5l7ALhH6eqKm7XMQBgLoDNZGlsrv1LUqgkP+OuVt4E=,tag:NdDgUEQ5zKFKNjfr8vJHcQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
