apiVersion: v1
kind: Secret
metadata:
    name: demoapp-credentials
    namespace: demoapp
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:Gu7f29c=,iv:1p7Z92aXxBfZOSUauWEx6s6s533ClTNgK9roce3Wj20=,tag:U8K2RVfP27V35k5PIWmrWw==,type:str]
    password: ENC[AES256_GCM,data:7k88mLdpnWRZEg==,iv:jYK/xD6SAKNXP4X64pJ8WLC8MyYGlZ+FeL6o+fAcYnA=,tag:lDIUuT/tLdTmZ/iK0mXFjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://azure-k8s-vault.vault.azure.net
          name: sops-key
          version: be5fd85dd8f64990b9ac687f8a4e0394
          created_at: "2021-06-09T20:05:20Z"
          enc: reBWf69ZkYp3ptHMBNJPiwy3p65b9KJjVP3tEArdM4RjjYabVQx5Rwg1h3u8pQNDIp-zbUhLJu_fT3GbI84erVRoV9yp8nxOg-Ut7yBOaaFJg_1t4Y0yAO4XHC0BilOQgM8760_HD7ORPhIcxCqp8XeqnEuKsedQl1s4kK4P_r5eqNw263A4nYRvwL17ZN7my1o3k2mgFUW_cEutSfTzRwxz4LhT6bdp3Xa_x6j87BSyxqpsNlBxKQbBqQ4fUI30-jCqj_amHoGt6ulx03jlsC7RcpPHpJvS3R44NT8Z2ZV862yfdY8v2wTsqowLzexaC63gfExehslB7Ts7hiHuWg
    hc_vault: []
    age: []
    lastmodified: "2021-06-09T20:05:21Z"
    mac: ENC[AES256_GCM,data:pZXYVZgBQhNUqwNEbUQ8J7G8XBsVQcXXpwGPls+9sF7VA8z3Mqc2eZ9N6mC66uo8XpFzdPBTzEnYOCQCx/GnJZ/GCdJcx56fK9YsTo6q3EJEzCVteQak6XqA3JgPneFdXKOcVHqYdFJ3Ipdn4CjYRCq6MNuU9vxVvas5VU/gNSk=,iv:1P9YCOKF9EInf6WnpRNZyvXNn8pDoIVipmdaOfeGMj0=,tag:YXbD5DlozziEEeWKrPz3/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
