---
apiVersion: v1
kind: Service
metadata:
  name: demoapp
  namespace: demoapp
spec:
  type: LoadBalancer
  selector:
    app: demoapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
