---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aad-pod-identity
  namespace: flux-system
spec:
  chart:
    spec:
      chart: aad-pod-identity
      sourceRef:
        kind: HelmRepository
        name: aad-pod-identity
      version: 4.1.1
  install: {}
  interval: 5m0s
  releaseName: aad-pod-identity
  targetNamespace: kube-system

