---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: akv2k8s
  namespace: flux-system
spec:
  chart:
    spec:
      chart: akv2k8s
      sourceRef:
        kind: HelmRepository
        name: spv-charts
      version: '>=2.0.0-0'
  install:
    crds: Create
  interval: 5m0s
  releaseName: akv2k8s
  targetNamespace: kube-system
  upgrade:
    crds: CreateReplace

