apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-credentials
  namespace: default
spec:
  encryptedData:
    password: AgAozmwNKmzD+O6KJ7db3Xl9BOeJg3BFLECL32nZYOVr5qECn0lY12CNXWvMj2unP9ux0ZMJpRVqLfRv/gmno2da4l6HyJEwjofA4w3QtmKcDWQhV9N3J1UshWZ9MZ2uAITqJ48kV+o3rfEB649H9aM+whmJ0qDV6vxWpvwp920opAeaadOPFN2/phxbDJayjIZeUc/bQ0mrX3EgJiFEZMkjrGXk6B/gmyG33wUgEXBeLI81JRnjn9yoFkUfG4Kwyn8o2nZpJwDXn5+MBLlEBpBKtIl4L1qvIOhvFF+wj61+gUOP1p8lLeUIZicMmFtXed6oFush6gj35ZZK4FiRjvlPaYBWsx3N+y7l+tWyxTGAVPBGtyd8TN68Vut2Og58E0QMdIGQbICr5zn/OcETPgsdoooAALXpFsRkXyitwBFW0KRZsJAarllS9x/h8+Zj96vRt5FW/ZGMyMA0Vt/xEB5RK2Af8H2t1ghdlYopYElH/cHYxyQ/b5qisE+oqdRbLryLrCdu+R6+r1mqs+LeKtOAImI5tdAv89OlGUEVup629PC6/ZFSvCp/ZAQJtZgxgcZLQeL08XyBS2374ZlEBsbrHYT0PnJmpPk+azs9iUpDBPfkH8k4LR3Us34zN3FZuy27ZnsHm3uuXDWt1MEh6fBs0C6tzwC3aZ6NiinqSZsqnz97ImSpw7rSZK03GJ6QsBaX4Io3D3RNqYED
    username: AgAW7kMoVsZz22ehvD8xY66eKtc44RyFGKeDtZUZU29j7Hh4efAXebYYCmxtVvzlCOhr6VFLU1LMApCQpWnFn+0hVtLhRjqfD2Grb4ixmTDv81a159fsWT/lsEdzKKHG/NL+g4XjSbE360/tdY8M4zAy5geRPvR4qMKTEe7DrmgHQIuS1ehiMggV50RZAus4DG9cL8E1NBSN2/AU4D41CGpFWKlQZakOSdKja7von0ynSmjpDfl3c1AGPUTrVHp6cAiwSUSLfUog/3BjHkSRRrsveQ5iJ61Qv9Oe7ZBdY459GDYfpjGzqXWzX32m1GTSrA1vfC6SD/PCrv3bqrrbbva2aLzcMTE0Zc8gt6WLvBTDPY9R00XF3cYBvHPkXNcPd052AqeBUKWCahUXCaPD1v4BoeAIS6PUIiIqAnCvQhqNa18DaMRWocQmSU6pip1sK5foAUmWMGTTbv9keWkCaMc//o/S/KiMA65NleqnYg1229HCub4Vitv6OmJLlB4jFtEZeDAAbet9OnzgG4yGvBLCe1ytWZOYMHo3rdUo/XvAAUXXTH4OdM2dCM0Yg0gwkV29rDnEIguFVeJOvOIngaw1UamVhRVpurV+NW8SE2U+7HpC6RKI1TDfHgqoUkukdwM0vzhnYkcATk91vEJBT7D2BfnyTdiktys+hHkGYMetYsrEPBYWOZ9kxbfDUKtjepf1BMmIdA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: app-credentials
      namespace: default
    type: Opaque

