apiVersion: v1
kind: Secret
metadata:
    name: demoapp-credentials
    namespace: demoapp
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:0arHmEI=,iv:8q1DqRW4lcddW6prf2c0ZHnmvuIXu13K77PzkAxuSa8=,tag:cQcxsEUICuCTPLBH7hDOaw==,type:str]
    password: ENC[AES256_GCM,data:r0em4xAshXwzzQ==,iv:jCcadgvqNqMLDagrWXskjn2VYBDGtbnuy01o2+YkhZ8=,tag:GTkWkI6LvRpqkHur5V9cug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://azure-k8s-vault.vault.azure.net
          name: sops-key
          version: b397f757c60142a8adae02536a27b0b4
          created_at: "2021-06-20T15:14:28Z"
          enc: piR5sxaKH-VKGCZg26K1IC8mc9yekHTybRttlL1SJQf4sqQ15cgwvN7gfNucbgv2kBICIBAHalDEw6KmXnVbIJmpP6_HZCu0ljYbnOXampJMBxunLN9X5ch0yT5vxlAm0I2cfZj3J9Ky80-ON8tsOxJ7tHbENiB1dfKb-rT_uEZ5FQ4byDcsz9IynkQbW_T-XrutGSx92u4JegNct5_7UQbtvS6an-A5kDDlfK94rn6enn-Vgu3MZC6jzNHxh4PadnITWYWhhKQPk6V1MAHz4c7d95id91oUKsktJ7GQClAnXf9pBIfQX_2-vVH03ZS_71MUGzqLj36_-TI9nLI6MQ
    hc_vault: []
    age: []
    lastmodified: "2021-06-20T15:14:29Z"
    mac: ENC[AES256_GCM,data:r347htjWCKg0nw+hotFd/erpsqF2ymQg5at0z6HN/YseV4alBwLepEYdUsiqah38HgyFy+dWrLDwRfxPiaVySuKpTyO/6GdWOYjYvpOjdeBUzC3zPeuSPCnJU77C5jxB4jwDHuR6mzdLRvmiQsOE/aZ0XOGK8UYU/z+Tx+N4Sw8=,iv:OGFoU6wVttEip3QgtxBan6bGACuYpOCq6g0a7ibCayo=,tag:+7RsyGQ+HlUeYC4U3AmGOg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
