---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: externaldns
  namespace: flux-system
spec:
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: bitnami
  valuesFrom:
  - kind: Secret
    name: cftoken
  interval: 5m0s
  releaseName: externaldns
  targetNamespace: default