{{- $namespace := .Release.Namespace }}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-keyvault
  namespace: {{ $namespace }}
spec:
  provider: azure
  secretObjects:
  - secretName: credentials
    type: Opaque
    data:
    - objectName: "admin"
      key: client-password
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    resourceGroup: "{{ .Values.azure.resourcegroup_name }}"
    keyvaultName: "{{ .Values.azure.keyvault_name }}"
    subscriptionId: "{{ .Values.azure.subscription_id }}"
    tenantId: "{{ .Values.azure.tenant_id }}"
    objects: |
      array:
        - |
          objectName: admin
          objectType: secret
