apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sample-app-ingress
  namespace: sample-app-ingress
spec:
  releaseName: sample-app-ingress
  chart:
    git: https://github.com/danielscholl/edge-validate.git
    path: charts/nginx-ingress
    ref: main
  values:
    image:
      repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
      tag: "0.32.0"
    replicaCount: 3