apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sample-app
  namespace: sample-app
spec:
  releaseName: sample-app
  chart:
    git: https://github.com/danielscholl/edge-validate.git
    path: charts/hello-arc
    ref: main
  values:
    image:
      repository: danielscholl/hello-arc
      tag: latest
    replicaCount: 1
    env:
      name: MESSAGE
      value: Edge App Demo!
