---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: istio-install
  namespace: istio-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/danielscholl/edge-validate
