---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: istio-system
  namespace: flux-system
spec:
  dependsOn:
    - name: istio-operator
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: istio-install
  path: ./deploy/istio/system
  prune: true
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: istiod
      namespace: istio-system
    - apiVersion: apps/v1
      kind: Deployment
      name: prometheus
      namespace: istio-system
    - apiVersion: apps/v1
      kind: Deployment
      name: flagger
      namespace: istio-system
